# This is a basic workflow that is manually triggered

name: Cut off release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: Examine branch
      run: |
        myBranch=$GITHUB_REF_NAME
        echo "+++++++ $myBranch"
        if [ $myBranch != "main" ];
        then
          echo "Can only run on 'main' branch"
          exit 1
        fi
        echo "Branch check passed"
        exit 0
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main
    - uses: fregante/setup-git-user@v1

    - name: Extract version
      id: extract_version
      uses: Saionaro/extract-package-version@v1.0.6
      # From now you can access the version
    - name: Print version
      run: echo ${{ steps.extract_version.outputs.version }}

    - name: Bump release version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.0.2
      with:
        current-version: ${{ steps.extract_version.outputs.version }}
        version-fragment: 'feature'
    - name: Switch to new branch if it's not exist yet
      id: new_branch
      outputs:
          desiredBranch: ${{ steps.step1.outputs.test }}      
      run: |
        echo ${{ steps.bump_version.outputs.next-version }}
        existInRemote=$(git ls-remote --heads origin $DESIRED_BRANCH)
        if [[ -z ${existInRemote} ]]; then
            echo "Branch '$DESIRED_BRANCH' not exists yet"
        else
            echo "Branch '$DESIRED_BRANCH' already exists. PLease remove it and restart workflow"
            exit 1
        fi
        git checkout -b $DESIRED_BRANCH
        echo "::set-output desiredBranch=$DESIRED_BRANCH"
  
    - name: Update version in package.json
      uses: jossef/action-set-json-field@v2
      with:
        file: package.json
        field: version
        value: ${{ steps.bump_version.outputs.next-version }}

    - name: Commit to local git branch
      run: |
        git add --all
        git commit -m "bump version to '${{ steps.bump_version.outputs.next-version }}'"
        echo "####  ${{ steps.new_branch.outputs.desiredBranch }}"
        git push --set-upstream origin ${{ steps.new_branch.outputs.desiredBranch }}

    # - name: Push as new release branch
    #   uses: s0/git-publish-subdir-action@develop
    #   env:
    #     REPO: self
    #     BRANCH: 'release/${{ steps.bump_version.outputs.next-version }}'
    #     FOLDER: $GITHUB_WORKSPACE
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Create Release branch
    #   id: create_release_branch
    #   uses: peterjgrainger/action-create-branch@v2.2.0
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     branch: 'release/${{ steps.bump_version.outputs.next-version }}'

    # - name: Check branch creation result
    #   run: |
    #     if [ ${{ steps.create_release_branch.outputs.created }} == true ];
    #     then
    #       echo "New release branch 'release/${{ steps.bump_version.outputs.next-version }}' created."
    #       exit 0
    #     fi
    #     echo "Failed to create release branch 'release/${{ steps.bump_version.outputs.next-version }}'. Please check if it's already exist."
    #     exit 1

